### ISSUE TITLE
[Bug]: Project name needs to change and so does the refences in the repo

### ISSUE THREAD

**Issue by doaonduty** [IBM/opentalaria#9]
### Contact Details

doaonduty@pm.me

### What happened?

Project name needs to change and all the references in the code

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladoatanasov** [comment]
This was addressed in https://github.com/IBM/opentalaria/pull/11. Thank you @doaonduty
